# Generated by Django 4.0.5 on 2022-06-12 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_remove_lesson_course_lesson_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subject',
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject_id',
            field=models.ForeignKey(default=2022, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.subjects'),
            preserve_default=False,
        ),
    ]
